from typing import Annotated, List, TypedDict, Optional
import operator
from langchain_core.messages import BaseMessage

class NaviState(TypedDict):
    # The core task from the user
    task: str
    # The step-by-step breakdown generated by the Planner
    plan: List[str]
    # Conversational memory and thought process
    history: Annotated[List[BaseMessage], operator.add]
    # Inventory of currently available tool names
    inventory: List[str]
    discovery_data: str
    # The code for a tool being currently built/refined
    generated_tool_code: Optional[str]
    # Last error message encountered during execution
    last_error: Optional[str]
    # Counter for the self-learning loop (max 5)
    retry_count: int
    # Safety flag for Human-in-the-loop
    user_approved: bool
    past_strategies: Annotated[List[str], operator.add]
    # Final output to the user
    final_answer: Optional[str]
    packages: List[str]
